name: News Automator

on:
  schedule:
    - cron: '30 1-17 * * *'  
    - cron: '30 18-20 * * *'  
  workflow_dispatch:  

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
        
    - name: Run News Automator
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        INSTAGRAM_ID: ${{ secrets.INSTAGRAM_ID }}
        INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
      run: python app.py
